### ISSUE TITLE
Add i2b2 conventions document to ETL service

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#14]
The document is [here](https://github.com/PEDSnet/Data_Models/blob/master/i2b2/V2/docs/i2b2_pedsnet_v2_etl_conventions.md). The tasks are:
- [ ] Add new routes for each document by name, e.g. `/pedsnet` and `/i2b2`
- [ ] Replace root endpoint with service information

@aaron0browne @murphyke What are your thoughts on the semantic version of these documents? Should the major version be included in the path? One approach could be support `/pedsnet/<version>` that returns a snapshot of the document, while the `/pedsnet` would always return the latest. This of course requires snapshotting the documents themselves.

**Comment by murphyke** [comment]
So that's the version of the document and not the version of the data model to which it applies, right?  Is the primary use case to grab the latest version of the ETL conventions document associated with a particular version of a data model?  It seems like the current state of affairs is to version the ETL conventions documents implicitly with the version of the data model (and make use of timestamps and git hashes/history when necessary).

**Comment by bruth** [comment]
That is a good question. My assumption is that the ETL conventions implicitly targets the latest data model definitions they apply to (PEDSnet and i2b2). The timestamp will be used to coordinate which conventions documents pertain to which version of the data model. So if a version is published, the last conventions document will be pinned to that version.

**Comment by gracecodes144** [comment]
I think @bruth is right about the conventions to data model version targeting, so far, in that the connection (beyond major version number) has been implicitly based on timestamp.

That seems to be a workable strategy moving forward, except that I would like to formalize the connection all the way down to the micro version number of the data model. So the semantic version of the documents would be the maj.min.micro of the data model, plus a timestamp from the actual document. This would allow change in the conventions document within each version of the data model without introducing too much complexity.

Perhaps we should introduce the exact data model version somewhere in the conventions document, in order to formalize a review process with each new data model version. So workflow would be "increment data model version in data-models" -> "check conventions document for any needed changes" -> "confirm compatibility by incrementing data model version in conventions document". Does that make sense?

In terms of the endpoints, I think the following make sense given our conversation:
- `/pedsnet` returns the latest
- `/pedsnet/all` returns a list of links to all versions
- `/pedsnet/2.0.0/` returns the latest document tied to data model version 2.0.0
- `/pedsnet/2.0.0/all` returns a list of links to all document versions tied to version 2.0.0
- `/pedsnet/2.0.0/<timestamp>` returns a specific timestamp version of the document, which is tied to 2.0.0 data model version
