### ISSUE TITLE
Add process for tracking vocabulary files

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#5]

**Comment by gracecodes144** [comment]
Here's the two vocab packages in question. https://upenn.app.box.com/s/g5m9xzffjncr6lgiq34dxd6bh1wx5c52

The one dated earlier is the one we gave to sites for this V2 data extraction. The later one should have more CPT codes.

**Comment by bruth** [comment]
Attributes of the concepts file:
- `concept_id`
- `concept_name`
- `domain_id`
- `vocabulary_id`
- `concept_class_id`
- `standard_concept`
- `concept_code`
- `valid_start_date`
- `valid_end_date`
- `invalid_reason`

The `domain_id` will be used as partition key for concepts. The `concept_id` will be used as the entity identifier. Two questions for @aaron0browne and @burrowse:
- Which of these attributes are in conflict the most?
- Can any of these attributes be omitted from being tracked because they are redundant identifiers or aren't worth tracking?

**Comment by burrowse** [comment]
Conflicts:
- `Concept_id` There could be possible collision, we haven't confirmed this but I fear that there is potential for this to happen. I don't know how strict the boundaries for vocabularies are in the concept creation world
- `Domain_id` Addition or deletion of domains as the vocabulary expands
- `Vocabulary_id` Addition or deletion of vocabularies as the vocabulary expands
- `Concept_class_id` We had an issue this vocabulary where there was an error in the vocabulary and this changed for a significant amount of DRGs, so this has some potential to also change.
- `Standard_Concept` If a concept becomes invalid this column becomes null
- `Concept_code` Addition or deletion of codes as the vocabulary expands
- `Valid_Start_date` Could be good to track so you could determine the period of time the concept was valid for
- `Valid_End_Date` This column changes if a concept becomes invalid
- `Invalid_Reason` If a concept is invalid or deprecated this column is populated otherwise blank

Redundant:

Could be `concept_name`... I believe if the name or methodology changes then the concept itself is deprecated or made invalid, so the name itself won't change but a new concept will be added.

For other comments:
It may be useful to also sort/partition by `Vocabulary_ID`, as one vocabulary can span multiple domains. 

Example:
`select distinct domain_id from chop_pedsnetv2.concept where vocabulary_id='LOINC';`

| domain_id |
| --- |
| Meas Value |
| Observation |
| Measurement |

**Comment by bruth** [comment]
Very useful thanks. So is the fundamental reason for tracking these concepts because `concept_id` is supposed to be unique but isn't? Or are the vocabularies being used by sites not consistent?

**Edit:** grammar.

**Comment by burrowse** [comment]
I think there are a few reasons really:
- Yes, there is the potential that they could not be unique (because we don't know the boundaries) although we expect them to be
- Yes, there are vocabularies being published very frequently that differ between distribution
- Concepts that are used in the sites ETL/ ETL Conventions could change in the underlying vocabularies on the OHDSII side, which is a priority to keep track of/be aware of since this impacts our workflow directly (most importantly)
- The concepts are expected to expand and grow overtime by domain, by vocabularies etc..  In a very simple case we can use the tracking tool to ensure we observe that. (Eg. To ensure we don't receive a vocabulary that has 100 Loinc codes by error when there are 100,000+.
- For concepts that become invalid, tracking this could inform a user when their particular code was valid for their study within the PEDSnet data network. (An example of this would be the explanation of finding individuals with unknown race in our v1 versus v2 data, using the code `8551` for v1 and the code `44814653` for v2 being able to track/demonstrate that 8551 was deprecated as of 2014-07-31)

`select * from chop_pedsnetv2.concept where concept_id=8551`

| concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 8551 | UNKNOWN | Gender | Gender | Gender |  | U | 1970-01-01 | 2014-07-31 | D |

`select * from chop_pedsnetv2.concept where concept_id=44814653`

| concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 44814653 | Unknown | Observation | PCORNet | Undefined |  | Generic-UN | 1970-01-01 | 2099-12-31 |  |

**Comment by bruth** [comment]
After further discussion with @burrowse and @l-k-, the primary issue is that:
- Sites may be using a different version of the vocabulary than the DCC. This causes conflicts during data loading or data quality analysis which requires manual intervention, back and forth with the site, or refresh export from the site.

The primary cause is:
- The OMOP and PEDSnet vocabularies are published with undisclosed/unknown changes without an explicit versioning method. This makes it difficult to coordinate which version should be used across sites.

The functionality of this service will:
- Pull down new versions of vocabularies (based on timestamp or MD5)
- Load vocabularies into Origins
- Query Origins for changes in the vocabularies
- Notify site contacts when a vocabulary changes

**Comment by murphyke** [comment]
Riffing on Byron's comment about the primary issue, what do you think about these changes to our workflow: 1) PEDSnet always versions its vocabulary releases (Charlie?), 2) the vocabulary version gets declared in the site metadata, and 3) the vocab version becomes a parameter of the load process, so the vocab version can be validated.

**Comment by bruth** [comment]
It seems that the DCC should be the one distributing the vocabulary to sites, not having the sites download from an external source.

**Comment by murphyke** [comment]
Yeah, Charlie's Box URLs are both of those rolled into one (DCC-directed and external source); regardless of the source, the sites still have to load the right thing in the right database at the right time.  It might also be good for the DCC to add a vocab_metadata table to the vocabulary that would record the version.  (How nice would it be to be able to conclusively confirm what version of vocabulary you've been using?)  The other procedural thing that should change is that the DCC requests for data from the sites should include the specific vocabulary version.

**Comment by bruth** [comment]
@burrowse @murphyke Has there been any more thoughts about the process for managing this re: the sites? As long as the vocabularies are _regulated_, the sites shouldn't have a problem. I still think it is worthwhile to have some way of knowing what changed when we use a new export from OHDSI. What do either you typically do when you find an inconsistency with the previous version?

**Comment by murphyke** [comment]
I'm not usually on the front lines finding such inconsistencies.

Aaron and Charlie are the only people who have built vocabularies.  We should have that procedure documented in the dcc repo somewhere, but I don't know if/where it is.  It may be possible that the person doing the build doesn't really know what has changed and just places trust in OHDSI.  The [OMOP vocab download page](http://www.ohdsi.org/web/athena/) shows update dates for components, and hopefully they are accurate.   

It's possible that low-level changes would be hard to interpret if automatically reported by a tool, but I guess we wouldn't know until we tried.  Such a tool might be more useful to OHSDI than to us.

I also don't know who communicates to the sites about new requests for data, but I think that discrepancies will be reduced if the vocab is versioned and the request for data is includes a specific vocab version with a link to it.

**Comment by bruth** [comment]
> It's possible that low-level changes would be hard to interpret if automatically reported by a tool, but I guess we wouldn't know until we tried. Such a tool might be more useful to OHSDI than to us.

I was thinking of another command line tool that would just compare two versions of concepts.csv file detect what changed based on the heuristics discussed earlier. We could certainly make it available for OHDSI to use, but it would be valuable for us to isolate changes so we can fix things and communicate them. Does this sound reasonable?

**Comment by murphyke** [comment]
That sounds reasonable.

**Comment by burrowse** [comment]
I think that would be a good start. We are moving towards creating snapshots of the vocabulary to package and deliver to sites with ddl and a stable ETL convention. The workflow for the snapshot that will be distributed for v2.1 (I think) has been to download the files from OHDSI's Athena site and add in any other vocabularies( GPI - because of licensing and PEDSNet - our custom vocabulary). Any discrepancies that we've discovered so far and in the past we've generally taken the issues up with ODHSI directly. 

From my prospective and wish list a tool that does the following would be very useful:
1. Provides general comparison counts (total,by domain, by vocabulary, concept names vs concept ids etc) to ensure that we see a general increase of codes and to ensure no one vocabulary is corrupted.
2. Provides a comparison of concept ids, they should be consistent between every generation of the vocabulary... as in concept id 1 shouldn't somehow become concept id 123 to ensure concept integrity.
3. Provides a check for the concepts in conventions document to ensure they are still valid concepts and keeps track of specific concepts from the document that have been deprecated.

**Comment by bruth** [comment]
Great list, thanks. I can assume that operating on the `concepts.csv` should be sufficient?

**Comment by burrowse** [comment]
I think for what I listed above the concepts.csv file would be sufficient.

Another  suggestion for a simple check would be ensuring that all the vocabularies from the vocabulary.csv file match the vocabulary ids in concepts.csv file

And also (reaching for the sky here -- we don't need this right away) another great check would be to ensure that the relationships we need in the concept_relationships.csv file are present and are incremented as well (Eg. our medication transformations are present and cover newly added concepts etc).

**Comment by bruth** [comment]
> would be to ensure that the relationships we need in the concept_relationships.csv file are present and are incremented as well

Where are the _relationships that we need_ defined?

**Comment by burrowse** [comment]
Hmm..They aren't defined in one place per say because it depends what each site has locally as a source code.

I think a good start would be to ensure that anything that maps to SNOMED(since we are using that for our diagnosis/condition occurrence golden standard) and RxNorm (our medication/drug exposure golden standard) is tracked.

This means that if the snomed/rxnorm concept is in concept_id_2 in concept_relationships.csv with a relationship id of 'Maps to' then we could keep track of it.

**Comment by bruth** [comment]
Preliminary tool created here #51. The [README](https://github.com/PEDSnet/tools/blob/issue-5/cmd/vocab/README.md) describes two basic commands. Please provide feedback and suggestions.
