### ISSUE TITLE
Packager Issue on Windows

### ISSUE THREAD

**Issue by WustlRob** [PEDSnet/tools#72]
We have been using C# version of the packager from our previous team for all previous submissions.  Tried using the current one and ran into the following issue:

F:\SSIS Information>data-models-packer.exe -comp .zip -out data input
2016/04/08 09:03:38 packer: configuration error: no compression extensions found

F:\SSIS Information>data-models-packer.exe -out data input
2016/04/08 09:03:55 packer: configuration error: no compression extensions found

We fell back to using the C# packager for our last submission (4/11/2016).

**Comment by gracecodes144** [comment]
Thanks for trying it out! The packer expects the filename to have compression extensions on it that match the selected compression method. So in the case of your first command, `data.zip`, and in the case of your second command, `data.tar.gz`, since gzipped tarfile is the default compression.

This behavior seems silly, in hindsight, and I'll be amending it in the future. Thanks for pointing it out!

**Comment by bruth** [comment]
Closing since this is not applicable to this repo.
